SELECT MOD (11,2) --MODULO RESIDUO
SELECT ROUND (10.54) -- REDONDEO 11
SELECT SQRT(9) -- RAIZ CUADRADA 
SELECT PI(); --VALOR DE PI
SELECT RANDOM(); --NUMERO RANDOM DOUBLE PRECISION
SELECT ABSOLUTE (-15.4) -- VALOR ABSOLUTO 15.4
SELECT ROUND (10.5467,2)-- REDONDEO DOS DECIMALES 10.55
SELECT SUM(codigo_ca) FROM tb_categorias;
SELECT MIN(codigo_ca) FROM tb_categorias;
SELECT MAX(codigo_ca) FROM tb_categorias;